---

name: YAML Lint

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install yamllint
        run: python3 -m pip install yamllint
      - name: Lint YAML files
        run: "yamllint -f github -d yamllint -d '{extends: default, rules: {line-length: disable}}' _data/guides.yml"