---

name: YAML Lint

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check if should skip
        id: should_skip
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"[skip ci]"* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Install yamllint
        if: steps.should_skip.outputs.skip == 'false'
        run: python3 -m pip install yamllint

      - name: Lint YAML files
        if: steps.should_skip.outputs.skip == 'false'
        run: "yamllint -f github -d yamllint -d '{extends: default, rules: {line-length: disable}}' _data/guides.yml"